# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Generated Dockerfile for Calculator MCP Server

# Build stage
FROM node:lts-alpine as builder
WORKDIR /app

# Install build dependencies
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

RUN npm install --ignore-scripts
RUN npm run build

# Production stage
FROM node:lts-alpine
WORKDIR /app

# Copy built files and production deps
COPY --from=builder /app/build ./build
COPY package.json package-lock.json ./

RUN npm install --production --ignore-scripts

# Expose no ports (uses stdio)
CMD ["node", "build/index.js"]
